---
- name: Unload processes
  ansible.windows.win_shell: Stop-Process -Name "{{ item }}" -Force
  loop: "{{ __unload_processes.lists.processes }}"
  ignore_errors: true
  no_log: true

- name: Inform user
  ansible.builtin.debug:
    msg: "{{ item }} stopped or already unexists"
  loop: "{{ __unload_processes.lists.processes }}"