isys:
  cpuLimits: "17.5"
  cpuRequests: "17.5"
  ramLimits: "76Gi"
  ramRequests: "76Gi"

kafkaClusters:
  qa-kafka:
    externalAccess: true
    size: minimal
    topics:
      test-topic:

  peinvest-appfarm-kafka:
    externalAccess: true
    size: large
    kafkaUI:
      enabled: true
    topics:
      internal.corp-actions.client-balances:
        config:
          retention.ms: "-1"
      internal.corp-actions-client-balance-store-changelog:
        config:
          retention.ms: "-1"
      internal.corp-actions-client-balance-store-repartition:
        config:
          retention.ms: "-1"
      internal.corp-actions.instruction-balance-dlq:
        config:
          retention.ms: "-1"
      internal.corp-actions.instruction-balance:
        config:
          retention.ms: "-1"
      internal.corp-actions.notification:
        config:
          retention.ms: "-1"
      internal.corp-actions.instruction:
        config:
          retention.ms: "-1"
      sinv.send-corp-actions-assignment-request:
        partitions: 3
        config:
          retention.ms: "-1"
      sinv.send-corp-actions-info-request:
        partitions: 3
        config:
          retention.ms: "-1"
      sofr-qmngr-mq-adapter-DLQ:
        partitions: 3
        config:
          retention.ms: "2592000000"
      sofr.mq-adapter.client-info:
        partitions: 3
      derivatives.requests.client.enriched:
        partitions: 3
      derivatives.requests.client.enriched.sofr.dlq:
        partitions: 3
        config:
          retention.ms: "2592000000"
      derivatives.requests.bank.enriched:
        partitions: 3
      derivatives.requests.bank.enriched.sofr.dlq:
        partitions: 3
        config:
          retention.ms: "2592000000"
      derivatives.deals.client.enriched:
        partitions: 3
      derivatives.deals.client.enriched.sofr.dlq:
        partitions: 3
        config:
          retention.ms: "2592000000"
      derivatives.deals.bank.enriched:
        partitions: 3
      derivatives.deals.bank.enriched.sofr.dlq:
        partitions: 3
        config:
          retention.ms: "2592000000"
      sofr.send-list-of-bonds-info:
        partitions: 3
      ips.rudata-sinkable-nominal:
        partitions: 3
      sofr.get-tax-report-info-request:
        partitions: 3
      sofr.get-tax-report-info-response:
        partitions: 3
      deals.marketschemes.moex-lnk:
        config:
          cleanup.policy: "compact"
      subcontracts.derivatives.active.moex-lnk:
        config:
          cleanup.policy: "compact"
      instruments.derivatives.active.moex-lnk:
        config:
          cleanup.policy: "compact"
      dias.send-depo-corp-actions-red-info-requests:
        partitions: 3
      sofr.send-le-brokerage-agreement-info-request:
        partitions: 3