env:
  LOGGING_RSHB: INFO
  LOGGING_RSHBI_INTECH: INFO
  LOGGING_SPRING: INFO
  LOGGING_SQL: DEBUG
  LOGGING_SQL_BASIC_BINDER: TRACE
  LOGGING_REPOSITORY: DEBUG

databases:
  - type: POSTGRESQL
    name: rshb_sofr_micro
    host: 10.7.118.211
    port: 5432
