# Информация о приложении
info:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  time: '@maven.build.timestamp@'

spring:
  application:
    name: kafka-postgres-adapter
  datasource:
    url: jdbc:postgresql://${APP_POSTGRESQL_HOST}:${APP_POSTGRESQL_PORT}/${APP_POSTGRESQL_NAME}
    username: ${APP_POSTGRESQL_USER}
    password: ${APP_POSTGRESQL_PASSWORD}
    hikari:
      maximum-pool-size: 20
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_schema: ${DB_SCHEMA_NAME}
app:
  postgres:
    schema: ${DB_SCHEMA_NAME}
  datasource:
    url: jdbc:postgresql://${APP_POSTGRESQL_HOST}:${APP_POSTGRESQL_PORT}/${APP_POSTGRESQL_NAME}
    username: ${APP_POSTGRESQL_USER}
    password: ${APP_POSTGRESQL_PASSWORD}
    pool-size: 30
  kafka:
     consumers:
       - topic: "sofr.send-nontrading-order-answer"
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_IPS_APPFARM_KAFKA}"
         group-id: "sofr.send-nontrading-order-answer"
       - topic: "sofr.send-nontrading-order-status-request"
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_IPS_APPFARM_KAFKA}"
         group-id: "sofr.send-nontrading-order-status-request"
       - topic: "ips.document-factory.requests"
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_IPS_APPFARM_KAFKA}"
         group-id: "ips.document-factory.requests"
       - topic: "sofr.get-brokerage-agreement-info-response"
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_IPS_APPFARM_KAFKA}"
         group-id: "sofr.get-brokerage-agreement-info-response"
       - topic: "sofr.get-legal-entity-report-response"
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_IPS_APPFARM_KAFKA}"
         group-id: "sofr.get-legal-entity-report-response"
       - topic: "sofr.send-bill-request"
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_IPS_APPFARM_KAFKA}"
         group-id: "sofr.send-bill-request"
       - topic: "sofr.send-bill-deal-request"
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_IPS_APPFARM_KAFKA}"
         group-id: "sofr.send-bill-deal-request"
       - topic: "sofr.send-list-of-bonds-info"
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_MYINVESTMENT_PEINVEST_APPFARM_KAFKA}"
         group-id: "sofr.send-list-of-bonds-info"
       - topic: "sofr.mq-adapter.client-info"
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_MYINVESTMENT_PEINVEST_APPFARM_KAFKA}"
         group-id: "sofr.mq-adapter.client-info"
       - topic: "derivatives.requests.client.enriched.sofr.dlq"
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_MYINVESTMENT_PEINVEST_APPFARM_KAFKA}"
         group-id: "derivatives.requests.client.enriched.sofr.dlq"
       - topic: "derivatives.requests.bank.enriched.sofr.dlq"
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_MYINVESTMENT_PEINVEST_APPFARM_KAFKA}"
         group-id: "derivatives.requests.bank.enriched.sofr.dlq"
       - topic: "derivatives.deals.client.enriched.sofr.dlq"
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_MYINVESTMENT_PEINVEST_APPFARM_KAFKA}"
         group-id: "derivatives.deals.client.enriched.sofr.dlq"
       - topic: "derivatives.deals.bank.enriched.sofr.dlq"
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_MYINVESTMENT_PEINVEST_APPFARM_KAFKA}"
         group-id: "derivatives.deals.bank.enriched.sofr.dlq"
       - topic: "sofr.get-tax-report-info-response"
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_MYINVESTMENT_PEINVEST_APPFARM_KAFKA}"
         group-id: "sofr.get-tax-report-info-response"
       - topic: "ips.orchestration.update-process.sofr"
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_IPS_APPFARM_KAFKA}"
         group-id: "ips.orchestration.update-process.sofr"
       - topic: "sofr.send-le-brokerage-agreement-info-request"
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_MYINVESTMENT_PEINVEST_APPFARM_KAFKA}"
         group-id: "sofr.send-le-brokerage-agreement-info-request"
     producers:
       - topic: maks.transfer-rates.universal-json
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_MAKS_MAKS_KAFKA_MAIN}"
       - topic: sofr.get-legal-entity-report-request
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_IPS_APPFARM_KAFKA}"
       - topic: sofr.send-nontrading-order-request
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_IPS_APPFARM_KAFKA}"
       - topic: sofr.send-nontrading-order-status-answer
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_IPS_APPFARM_KAFKA}"
       - topic: sinv.get-brokerage-report-info-request
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_IPS_APPFARM_KAFKA}"
       - topic: sofr.get-brokerage-agreement-info-request
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_IPS_APPFARM_KAFKA}"
       - topic: ips.cft.send-promissory-notes-acc-list
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_IPS_APPFARM_KAFKA}"
       - topic: dias.send-depo-corp-actions-red-info-requests
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_MYINVESTMENT_PEINVEST_APPFARM_KAFKA}"
       - topic: sofr.get-tax-report-info-request
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_MYINVESTMENT_PEINVEST_APPFARM_KAFKA}"
       - topic: ips.orchestration.sofr.send-ba-terms-req
         bootstrap-servers: "${APP_KAFKA_BOOTSTRAP_SERVERS_PLATFORM_IPS_APPFARM_KAFKA}"

logging:
  level:
    org:
      springframework:
        jdbc: DEBUG
        beans: DEBUG