spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: "corp_action"
    password: "corp_action"
    url: "jdbc:postgresql://localhost:5433/corp_action"
  liquibase:
    change-log: classpath:/db_changelog/release-1.0.0/cumulative.xml
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          lob:
            non_contextual_creation: true
        # Добавляем свойство для работы с JSONB
        temp.use_jdbc_metadata_defaults: false
        # Дополнительные настройки для PostgreSQL
        format_sql: true
        use_sql_comments: true

kafka:
  notification-from-diasoft:
    topic: "${KAFKA_TOPIC_NOTIFICATION_FROM_DIASOFT:notification-from-diasoft}"
    topic-dlq: "${KAFKA_TOPIC_NOTIFICATION_FROM_DIASOFT_DLQ:notification-from-diasoft.dlq}"
    consumer:
      bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS_NOTIFICATION_FROM_DIASOFT:localhost:9092}"
      group-id: "${KAFKA_GROUP_NOTIFICATION_FROM_DIASOFT:corp-action-notification-from-diasoft}"
      concurrency: 3
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session.timeout.ms: 30000
        max.poll.interval.ms: 60000
        metadata.max.age.ms: 30000
  internal-notification:
    topic: "${KAFKA_TOPIC_INTERNAL_NOTIFICATION:internal-notification}"
    consumer:
      bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS_INTERNAL_NOTIFICATION:localhost:9092}"
      group-id: "${KAFKA_GROUP_INTERNAL_NOTIFICATION:corp-action-internal-notification}"
      concurrency: 3
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        session.timeout.ms: 30000
        max.poll.interval.ms: 60000
        metadata.max.age.ms: 30000
    producer:
      bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS_INTERNAL_NOTIFICATION_PRODUCER:localhost:9092}"
      security:
        protocol: PLAINTEXT
      producer:
        retries: ${KAFKA_PRODUCER_RETRIES:3}
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        acks: ${KAFKA_PRODUCER_ACKS:all}
        properties:
          max.block.ms: ${KAFKA_PRODUCER_TIMEOUTS_MS:3000}
          max.request.size: 10485760
  internal-notification-owner-balance:
    topic: "${KAFKA_TOPIC_INTERNAL_NOTIFICATION_OWNER_BALANCE:internal-notification}"
    consumer:
      bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS_INTERNAL_NOTIFICATION_OWNER_BALANCE:localhost:9092}"
      group-id: "${KAFKA_GROUP_INTERNAL_NOTIFICATION_OWNER_BALANCE:internal-notification-owner-balance}"
      concurrency: 3
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        session.timeout.ms: 30000
        max.poll.interval.ms: 60000
        metadata.max.age.ms: 30000
  internal-instruction:
    topic: "${KAFKA_TOPIC_INTERNAL_INSTRUCTION:internal-instruction}"
    consumer:
      bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS_INTERNAL_INSTRUCTION:localhost:9092}"
      group-id: "${KAFKA_GROUP_INTERNAL_INSTRUCTION:corp-action-internal-instruction}"
      concurrency: 3
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        session.timeout.ms: 30000
        max.poll.interval.ms: 60000
        metadata.max.age.ms: 30000
    producer:
      bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS_INTERNAL_INSTRUCTION_PRODUCER:localhost:9092}"
      security:
        protocol: PLAINTEXT
      producer:
        retries: ${KAFKA_PRODUCER_RETRIES:3}
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        acks: ${KAFKA_PRODUCER_ACKS:all}
        properties:
          max.block.ms: ${KAFKA_PRODUCER_TIMEOUTS_MS:3000}
          max.request.size: 10485760
  instruction-to-diasoft:
    topic: "${KAFKA_TOPIC_INSTRUCTION_TO_DIASOFT:instruction-to-diasoft}"
    producer:
      bootstrap-servers: "${KAFKA_BOOTSTRAP_SERVERS_INSTRUCTION_TO_DIASOFT:localhost:9092}"
      security:
        protocol: PLAINTEXT
      producer:
        retries: ${KAFKA_PRODUCER_RETRIES:3}
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        acks: ${KAFKA_PRODUCER_ACKS:all}
        properties:
          max.block.ms: ${KAFKA_PRODUCER_TIMEOUTS_MS:3000}
          max.request.size: 10485760

# Параметры админских эндпоинтов
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure.include: info, health, prometheus, loggers
      path-mapping:
        prometheus: metrics
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    prometheus:
      enabled: true
    loggers:
      enabled: true

logging:
  level:
    ru.rshb: info
    ru.rshbintech: info
    org.springframework: info
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    ru.rshbintech.it_invest.backoffice.myinvestment.corp.action.repository: DEBUG

springdoc:
  api-docs:
    resolve-schema-properties: true
    path: /api
  swagger-ui:
    path: /api/doc
    layout: BaseLayout
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true