spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: "corp_action"
    password: "corp_action"
    url: "jdbc:postgresql://localhost:5433/corp_action"
  liquibase:
    change-log: classpath:/db_changelog/release-1.0.0/cumulative.xml

kafka:
  notification-from-diasoft:
    topic: "topic1"
    topic-dql: "topic1.dlq"
    consumer:
      bootstrap-servers: "localhost:9092"
      group-id: "corp-action"
      concurrency: 3
      properties:
        session.timeout.ms: 30000
        max.poll.interval.ms: 60000
        metadata.max.age.ms: 30000
  internal-notification:
    topic: "topic1"
    consumer:
      bootstrap-servers: "localhost:9092"
      group-id: "corp-action"
      concurrency: 3
      properties:
        session.timeout.ms: 30000
        max.poll.interval.ms: 60000
        metadata.max.age.ms: 30000
    producer:
      bootstrap-servers: "localhost:9092"
      security:
        protocol: PLAINTEXT
      producer:
        retries: ${KAFKA_PRODUCER_RETRIES:3}
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        acks: ${KAFKA_PRODUCER_ACKS:all}
        properties:
          max.block.ms: ${KAFKA_PRODUCER_TIMEOUTS_MS:3000}
          max.request.size: 10485760
  internal-instruction:
    topic: "topic1"
    consumer:
      bootstrap-servers: "localhost:9092"
      group-id: "corp-action"
      concurrency: 3
      properties:
        session.timeout.ms: 30000
        max.poll.interval.ms: 60000
        metadata.max.age.ms: 30000
    producer:
      bootstrap-servers: "localhost:9092"
      security:
        protocol: PLAINTEXT
      producer:
        retries: ${KAFKA_PRODUCER_RETRIES:3}
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        acks: ${KAFKA_PRODUCER_ACKS:all}
        properties:
          max.block.ms: ${KAFKA_PRODUCER_TIMEOUTS_MS:3000}
          max.request.size: 10485760
  instruction-to-diasoft:
    topic: "topic333"
    producer:
      bootstrap-servers: "localhost:9092"
      security:
        protocol: PLAINTEXT
      producer:
        retries: ${KAFKA_PRODUCER_RETRIES:3}
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        acks: ${KAFKA_PRODUCER_ACKS:all}
        properties:
          max.block.ms: ${KAFKA_PRODUCER_TIMEOUTS_MS:3000}
          max.request.size: 10485760

corp-action:
  job:
    consumer-rate: 10000
    consumer-batch-size: 50
    producer-rate: 10000
    producer-batch-size: 30

# Параметры админских эндпоинтов
management:
  endpoints:
    enabled-by-default: false
    web:
      base-path: /
      exposure.include: info, health, prometheus, loggers
      path-mapping:
        prometheus: metrics
  endpoint:
    info:
      enabled: true
    health:
      enabled: true
      probes:
        enabled: true
    prometheus:
      enabled: true
    loggers:
      enabled: true

logging:
  level:
    ru.rshb: info
    ru.rshbintech: info
    org.springframework: info
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    ru.rshbintech.it_invest.backoffice.myinvestment.corp.action.repository: DEBUG

springdoc:
  api-docs:
    resolve-schema-properties: true
    path: /api
  swagger-ui:
    path: /api/doc
    layout: BaseLayout
    display-request-duration: true
    show-extensions: true
    show-common-extensions: true