KAFKA_TOPIC_NOTIFICATION_FROM_DIASOFT: "notification-from-diasoft"
KAFKA_TOPIC_NOTIFICATION_FROM_DIASOFT_DLQ: "notification-from-diasoft.dlq"
KAFKA_BOOTSTRAP_SERVERS_NOTIFICATION_FROM_DIASOFT: "localhost:9092"
KAFKA_GROUP_NOTIFICATION_FROM_DIASOFT: "corp-action-notification-from-diasoft"
KAFKA_TOPIC_INTERNAL_NOTIFICATION: "internal-notification"
KAFKA_BOOTSTRAP_SERVERS_INTERNAL_NOTIFICATION: "localhost:9092"
KAFKA_GROUP_INTERNAL_NOTIFICATION: "corp-action-internal-notification"
KAFKA_BOOTSTRAP_SERVERS_INTERNAL_NOTIFICATION_PRODUCER: "localhost:9092"
KAFKA_TOPIC_INTERNAL_NOTIFICATION_OWNER_BALANCE: "internal-notification"
KAFKA_BOOTSTRAP_SERVERS_INTERNAL_NOTIFICATION_OWNER_BALANCE: "localhost:9092"
KAFKA_GROUP_INTERNAL_NOTIFICATION_OWNER_BALANCE: "internal-notification-owner-balance"
KAFKA_TOPIC_INTERNAL_INSTRUCTION: "internal-instruction"
KAFKA_BOOTSTRAP_SERVERS_INTERNAL_INSTRUCTION: "localhost:9092"
KAFKA_BOOTSTRAP_SERVERS_INTERNAL_INSTRUCTION_PRODUCER: "localhost:9092"
KAFKA_TOPIC_INSTRUCTION_TO_DIASOFT: "instruction-to-diasoft"
KAFKA_BOOTSTRAP_SERVERS_INSTRUCTION_TO_DIASOFT: "localhost:9092"
KAFKA_GROUP_INTERNAL_INSTRUCTION_VIEW: "KAFKA_GROUP_INTERNAL_INSTRUCTION_VIEW"
KAFKA_GROUP_INTERNAL_INSTRUCTION: "KAFKA_GROUP_INTERNAL_INSTRUCTION"
KAFKA_TOPIC_INTERNAL_INSTRUCTION_BALANCE: "KAFKA_TOPIC_INTERNAL_INSTRUCTION_BALANCE"
KAFKA_STREAM_TOPIC_PREFIX: "corp-actions"
KAFKA_STREAM_TOPIC_CLIENT_BALANCES_GLOBAL: "internal.corp-actions.client-balances"
KAFKA_STREAM_CLIENT_BALANCES_STORE: "KAFKA_STREAM_CLIENT_BALANCES_STORE"
LOGGING_RSHB: INFO
LOGGING_RSHBI_INTECH: INFO
LOGGING_SPRING: INFO
LOGGING_SQL: DEBUG
LOGGING_SQL_BASIC_BINDER: TRACE
LOGGING_REPOSITORY: DEBUG

APP_POSTGRESQL_USER: "corp_action"
APP_POSTGRESQL_PASSWORD: "corp_action"
APP_POSTGRESQL_HOST: "localhost"
APP_POSTGRESQL_PORT: 5433
APP_POSTGRESQL_NAME: "corp_action"