# Информация о приложении
info:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  time: '@maven.build.timestamp@'

# Параметры приложения
app:
  serviceName: ${info.name}

spring:
  application.name: fx-client-trades-service-sofr
  datasource:
    driver-class-name: org.postgresql.Driver
    url:
    username:
    password:

  kafka:
    bootstrap-servers: ${APP_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    producer:
      retries: ${KAFKA_PRODUCER_RETRIES:3}
      acks: ${KAFKA_PRODUCER_ACKS:all}
    dlq:
      interval: ${KAFKA_DLQ_INTERVAL:5000}
      attempts: ${KAFKA_DLQ_ATTEMPTS:5}
    topic:
      dlq: ${KAFKA_TOPIC_DLQ:fx.dlq}
      orders-client: ${KAFKA_TOPIC_ORDERS_CLIENT:fx.orders.client}
      trades-client: ${KAFKA_TOPIC_TRADES_CLIENT:fx.trades.client}

management:
  endpoints:
    access.default: none
    web:
      base-path: /
      exposure.include: info, health, prometheus, loggers
      path-mapping:
        prometheus: metrics
  endpoint:
    info:
      access: read_only
    health:
      access: read_only
      probes:
        enabled: true
    prometheus:
      access: read_only
    loggers:
      access: unrestricted