rshbintech:
  app:
    name: asudr-proxy-rsbank

spring:
  config:
    import: "optional:file:config/config.yml"
  datasource:
    url: jdbc:oracle:thin:@//${APP_ORACLE_HOST}:${APP_ORACLE_PORT}/${APP_ORACLE_NAME}
    username: ${APP_ORACLE_USER}
    password: ${APP_ORACLE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
  reactor:
    context-propagation: AUTO
  codec:
    max-in-memory-size: 10MB

mybatis:
  mapper-locations: classpath:/mybatis/**/*.xml
  configuration-properties:
    schema_name: ${APP_ORACLE_SCHEMA}
    condor_sofr_buffer_table_insert_stored_proc_name: ${app.fast-answer.condor-sofr-buffer-table-insert-stored-proc-name}
