rshbintech:
  app:
    name: asudr-proxy-rsbank

spring:
  config:
    import: "optional:file:config/config.yml"
  datasource:
    url: jdbc:postgresql://${APP_POSTGRES_HOST}:${APP_POSTGRES_PORT}/${APP_POSTGRES_DB}
    username: ${APP_POSTGRES_USER}
    password: ${APP_POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver
  reactor:
    context-propagation: AUTO
  codec:
    max-in-memory-size: 10MB

mybatis:
  mapper-locations: classpath:/mybatis/**/*.xml
  configuration-properties:
    schema_name: ${APP_POSTGRES_SCHEMA}
    condor_sofr_buffer_function_name: ${app.fast-answer.condor-sofr-buffer-function-name}