---
- name: Write new record
  ansible.builtin.win_shell: "echo '{{ date }} {{ time }} \t{{ jobnum }}\t{{ user_tag }}\tНа стенд #{{ stand }} установлен сервис rsbankws-proxy версии {{ release }}' >> {{ file }}"
  args:
    chdir: "{{ stand_dir }}"