psvc:
  name: Адаптер Kafka database
  description: >
    Интеграционный сервис для взаимодействия между Kafka и БД postgres
  istioSidecarSettings:
    limits:
      cpu: "400m"
      memory: "384Mi"
    requests:
      cpu: "10m"
      memory: "64Mi"

resources:
  limits:
    memory: 1024Mi
    cpu: 1
  requests:
    memory: 384Mi
    cpu: 100m

env:

strategyType: Recreate

probes:
  readinessProbe:
    initialDelaySeconds: 60
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 5
  livenessProbe:
    initialDelaySeconds: 60
    periodSeconds: 5
    timeoutSeconds: 3
    successThreshold: 1
    failureThreshold: 5