isys:
  cpuLimits: "72"
  cpuRequests: "72"
  ramLimits: "274Gi"
  ramRequests: "274Gi"
  roles:
    - code: DKK_STAFF
      description: Сотрудник ДКК
    - code: REPORT_MASTER
      description: Супер роль для сервиса отчетов

kafkaClusters:
  qa-kafka:
    externalAccess: true
    size: minimal
    topics:
      test-topic:

  peinvest-appfarm-kafka:
    externalAccess: true
    size: large
    kafkaUI:
      enabled: true
    topics:
      internal.corp-actions.client-balances:
        config:
          retention.ms: "-1"
      internal.corp-actions.client-balance-store-repartition:
        config:
          retention.ms: "-1"
      internal.corp-actions.client-balance-store-changelog:
        config:
          retention.ms: "-1"
      internal.corp-actions.instruction-balance:
        config:
          retention.ms: "-1"
      internal.corp-actions.notification:
        config:
          retention.ms: "-1"
      internal.corp-actions.instruction:
        config:
          retention.ms: "-1"
      sinv.send-corp-actions-assignment-request:
        partitions: 3
        config:
          retention.ms: "-1"
      sinv.send-corp-actions-info-request:
        partitions: 3
        config:
          retention.ms: "-1"
      sofr-qmngr-mq-adapter-DLQ:
        partitions: 3
        config:
          retention.ms: "2592000000"
      sofr.derivatives.fix:
        config:
          retention.ms: "1209600000"
      sofr.derivatives.fix.dlq:
        config:
          retention.ms: "-1"
      derivatives.requests.enriched.dlq:
        config:
          retention.ms: "-1"
      derivatives.deals.enriched.dlq:
        config:
          retention.ms: "-1"
      derivatives.requests.enriched.sofr.dlq:
        config:
          retention.ms: "-1"
      bank.marketplacecodes:
        config:
          cleanup.policy: "compact"
      instruments.derivatives.active:
        config:
          cleanup.policy: "compact"
      subcontracts.derivatives.active:
        config:
          cleanup.policy: "compact"
      rates.tickcosts:
        config:
          cleanup.policy: "compact"
      deals.marketschemes:
        config:
          cleanup.policy: "compact"
      commissions.types:
        config:
          cleanup.policy: "compact"
      commissions.parameters.plans:
        config:
          cleanup.policy: "compact"
      calendars.markets.derivatives.clearing:
        config:
          cleanup.policy: "compact"
      sofr.mq-adapter.client-info:
        partitions: 3
      derivatives.requests.client.enriched:
        partitions: 3
      derivatives.requests.client.enriched.sofr.dlq:
        partitions: 3
        config:
          retention.ms: "2592000000"
      derivatives.requests.bank.enriched:
        partitions: 3
      derivatives.requests.bank.enriched.sofr.dlq:
        partitions: 3
        config:
          retention.ms: "2592000000"
      derivatives.deals.client.enriched:
        partitions: 3
      derivatives.deals.client.enriched.sofr.dlq:
        partitions: 3
        config:
          retention.ms: "2592000000"
      derivatives.deals.bank.enriched:
        partitions: 3
      derivatives.deals.bank.enriched.sofr.dlq:
        partitions: 3
        config:
          retention.ms: "2592000000"
      sofr.send-list-of-bonds-info:
        partitions: 3
      ips.rudata-sinkable-nominal:
        partitions: 3
      sofr.get-tax-report-info-request:
        partitions: 3
      sofr.get-tax-report-info-response:
        partitions: 3
      deals.marketschemes.moex-lnk:
        config:
          cleanup.policy: "compact"
      subcontracts.derivatives.active.moex-lnk:
        config:
          cleanup.policy: "compact"
      instruments.derivatives.active.moex-lnk:
        config:
          cleanup.policy: "compact"
      dias.send-depo-corp-actions-red-info-requests:
        partitions: 3
      sofr.fx.raw:
        partitions: 6
        config:
          retention.ms: "1209600000"
      fx.dlq:
        partitions: 6
        config:
          retention.ms: "-1"
      fx.orders.client.enriched:
        partitions: 6
        config:
          retention.ms: "1209600000"
      fx.trades.client.enriched:
        partitions: 6
        config:
          retention.ms: "1209600000"
      fx.trades.client:
        partitions: 6
        config:
          retention.ms: "1209600000"
      fx.orders.client:
        partitions: 6
        config:
          retention.ms: "1209600000"
      fx.subcontracts.active:
        partitions: 3
        config:
          cleanup.policy: "compact"
      fx.subcontracts.active.moex-lnk:
        partitions: 3
        config:
          cleanup.policy: "compact"
      fx.marketschemes.moex-lnk:
        partitions: 3
        config:
          cleanup.policy: "compact"
      fx.commissions.types:
        partitions: 3
        config:
          cleanup.policy: "compact"
      fx.commissions.parameters.plans:
        partitions: 3
        config:
          cleanup.policy: "compact"
      fx.calendars.markets.clearing:
        partitions: 3
        config:
          cleanup.policy: "compact"
      fx.instruments:
        partitions: 3
        config:
          cleanup.policy: "compact"
      fx.instruments.moex-lnk:
        partitions: 3
        config:
          cleanup.policy: "compact"
      sofr.send-le-brokerage-agreement-info-request:
        partitions: 3
      sofr.bduiReport.requests:
        partitions: 3
        config:
          cleanup.policy: "compact"
      sofr.bduiReport.responses:
        config:
          cleanup.policy: "compact"
      sofr.bduiTags.updates:
        config:
          cleanup.policy: "compact"
      report-service-bff-user-reports-store-changelog:
        partitions: 3
        config:
          cleanup.policy: "compact"
      report-service-bff-user-tags-store-changelog:
        partitions: 3
        config:
          cleanup.policy: "compact"