---
- name: Clean artifact dir
  win_file:
    path: "{{ filepath | regex_replace('.zip', '') }}"
    state: absent

- name: Unzip the artifact
  win_shell: "Expand-Archive -Force {{ filepath }} {{ filepath | regex_replace('.zip', '') }}{{ jobid }}"