---
- name: Pre-create {{ proxy }}\bin
  win_file:
    path: "{{ proxy }}\\bin"
    state: directory
    
- name: Place new jar
  win_shell: xcopy /E /Y /F {{ jar }} "{{ proxy }}\bin"
  args:
    chdir: "{{ artifact }}\\bin"