# Информация о приложении
info:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  time: '@maven.build.timestamp@'

# Параметры админских эндпоинтов
management:
  endpoints:
    access.default: none
    web:
      base-path: /
      exposure.include: info, health, prometheus, loggers
      path-mapping:
        prometheus: metrics
  endpoint:
    info:
      access: read_only
    health:
      access: read_only
      probes:
        enabled: true
    prometheus:
      access: read_only
    loggers:
      access: unrestricted
spring:
  kafka:
    bootstrap-servers: ${APP_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    auto-offset-reset: earliest
    producer:
      retries: ${KAFKA_PRODUCER_RETRIES:3}
      acks: ${KAFKA_PRODUCER_ACKS:all}
    streams:
      application-id: ${KAFKA_APP_ID:fx-enrichment-service-app}
    dlq:
      interval: ${KAFKA_DLQ_INTERVAL:5000}
      attempts: ${KAFKA_DLQ_ATTEMPTS:5}
    topic:
      raw-orders: ${KAFKA_TOPIC_RAW_ORDERS:sofr.fx.raw.orders}
      raw-trades: ${KAFKA_TOPIC_RAW_TRADES:sofr.fx.raw.trades}
      orders-client-enriched: ${KAFKA_TOPIC_ORDERS_CLIENT_ENRICHED:fx.orders.client.enriched}
      trades-client-enriched: ${KAFKA_TOPIC_TRADES_CLIENT_ENRICHED:fx.trades.client.enriched}
      orders-client: ${KAFKA_TOPIC_ORDERS_CLIENT:fx.orders.client}
      trades-client: ${KAFKA_TOPIC_TRADES_CLIENT:fx.trades.client}
      subcontract-active: ${KAFKA_TOPIC_SUBCONTRACTS_ACTIVE:fx.subcontracts.active}
      subcontract-active-moex-lnk: ${KAFKA_TOPIC_SUBCONTRACTS_ACTIVE_MOEX_LNK:fx.subcontracts.active.moex-lnk}
      market-schemes-moex-lnk: ${KAFKA_TOPIC_MARKETSCHEMES_MOEX_LNK:fx.marketschemes.moex-lnk}
      commissions-types: ${KAFKA_TOPIC_COMMISSIONS_TYPES:fx.commissions.types}
      commission-plans: ${KAFKA_TOPIC_COMMISSIONS_PLANS:fx.commissions.parameters.plans}
      instruments: ${KAFKA_TOPIC_INSTRUMENTS:fx.instruments}
      instruments-moex-lnk: ${KAFKA_TOPIC_INSTRUMENTS_MOEX_LNK:fx.instruments.moex-lnk}
      dlq: ${KAFKA_TOPIC_DLQ:fx.dlq}