- name: Send build deployed telegram notification
  ansible.builtin.uri:
    url: https://api.telegram.org/{{ token }}/sendMessage
    method: POST
    body_format: json
    body:
      chat_id: "{{ telegram_chat_id }}"
      text: |
        На стенд #{{ stand }} установлен сервис <strong>rsbankws-proxy</strong> версии <strong>{{ release }}</strong>
      reply_markup:
        inline_keyboard:
          -
            - text: Конвейер
              url: "{{ joburl }}"
      parse_mode: html
  # no_log: True
  register: _telegram_notification_register
  ignore_errors: true
  retries: 10
  until: _telegram_notification_register.status == 200
  delegate_to: localhost