isys:
  cpuLimits: "17.5"
  cpuRequests: "17.5"
  ramLimits: "76Gi"
  ramRequests: "76Gi"

kafkaClusters:
  peinvest-appfarm-kafka:
    externalAccess: true
    size: large
    kafkaUI:
      enabled: true
    topics:
      sofr-qmngr-mq-adapter-DLQ:
        partitions: 3
        config:
          retention.ms: "2592000000"
      sofr.mq-adapter.client-info:
        partitions: 3
      sofr.send-list-of-bonds-info:
        partitions: 3
      ips.rudata-sinkable-nominal:
        partitions: 3
      sofr.get-tax-report-info-request:
        partitions: 3
      sofr.get-tax-report-info-response:
        partitions: 3
      dias.send-depo-corp-actions-red-info-requests:
        partitions: 3
      sofr.send-le-brokerage-agreement-info-request:
        partitions: 3