# Информация о приложении
info:
  name: '@project.name@'
  description: '@project.description@'
  version: '@project.version@'
  time: '@maven.build.timestamp@'

# Параметры админских эндпоинтов
management:
  endpoints:
    access.default: none
    web:
      base-path: /
      exposure.include: info, health, prometheus, loggers
      path-mapping:
        prometheus: metrics
  endpoint:
    info:
      access: read_only
    health:
      access: read_only
      probes:
        enabled: true
    prometheus:
      access: read_only
    loggers:
      access: unrestricted

spring:
  kafka:
    bootstrap-servers: ${APP_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    auto-offset-reset: latest
    producer:
      retries: ${KAFKA_PRODUCER_RETRIES:3}
      acks: {$KAFKA_PRODUCES_ACKS:all}
    streams:
      application-id: enrichment-derivative-deals
    dlq:
      interval: 1000
      attempts: 3
    topic:
      raw-data: ${KAFKA_TOPIC_RAW:sofr.derivatives.fix}
      requests: ${KAFKA_TOPIC_REQUESTS:derivatives.requests.bank.enriched}
      client-requests: ${KAFKA_TOPIC_CLIENT_REQUESTS:derivatives.requests.client.enriched}
      deals: ${KAFKA_TOPIC_DEALS:derivatives.deals.bank.enriched}
      client-deals: ${KAFKA_TOPIC_CLIENT_DEALS:derivatives.deals.client.enriched}
      contracts-moex-lnk: ${KAFKA_TOPIC_CONTRACTS_LINK:subcontracts.derivatives.active.moex-lnk}
      contracts: ${KAFKA_TOPIC_CONTRACTS:subcontracts.derivatives.active}
      instruments-moex-lnk: ${KAFKA_TOPIC_INSTRUMENTS_LINK:instruments.derivatives.active.moex-lnk}
      instruments: ${KAFKA_TOPIC_INSTRUMENTS:instruments.derivatives.active}
      calendar: ${KAFKA_TOPIC_CALENDAR:calendars.markets.derivatives.clearing}
      market-scheme-moex-lnk: ${KAFKA_TOPIC_MARKET_SCHEME:deals.marketschemes.moex-lnk}
      commission-types: ${KAFKA_TOPIC_COMMISSION_TYPES:commissions.types}
      commission-plans: ${KAFKA_TOPIC_COMMISSION_PLANS:commissions.parameters.plans}
      bank-mp-codes: ${KAFKA_TOPIC_BANK_MP_CODES:bank.marketplacecodes}
      dlq: ${KAFKA_TOPIC_DLQ:sofr.derivatives.fix.dlq}


